services:
  app:
    image: ghcr.io/slfhstd/flairtimercomment:v0.0.1
    container_name: bot-ftc-dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - /docker/data/flairtimercomment:/app/config

      
